[package]
name = "x402"
version = "1.0.0"
authors = []

[addresses]
x402a = "0xc7e1ae48502e9d236288827ade5ac916ccd7454f2136856cdf002820494c7f36"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
